##  =============== BEGIN ASSESSMENT HEADER ================
### @file Lab2/Makefile
### @brief Lab 2 Spring 2015
###
### @author Alexander Puh [apuh001@ucr.edu]
### @date 4/13/2015
### @SID: 861162817
###
### @par Enrollment Notes 
###     Lecture Section: 001
### @par
###     Lab Section: 022
### @par
###     TA: Mandar
##  ================== END ASSESSMENT HEADER ===============


all: a.out run

a.out: main.cpp 
	g++ -std=c++11 -Wall -Werror -pedantic main.cpp 

run: a.out
	./a.out
	
clean:
	rm a.out 